name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  # hive no sql database
  hive: ^2.2.3
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  # path
  path_provider: ^2.1.2
  # get it singleton
  get_it: ^7.6.4
  # equatable
  equatable: ^2.0.5
  # state manager
  flutter_bloc: ^8.1.3
  # interceptor
  dio: ^5.3.3
  dio_retry_plus: ^2.0.3
  # internet check
  internet_connection_checker: ^1.0.0+1
  # box
  gap: ^3.0.1
  # svg render
  flutter_svg: ^2.0.7
  # cached image
  cached_network_image: ^3.3.0
  # native splash
  flutter_native_splash: ^2.3.3
  # router
  go_router: ^13.2.0
  #zoom tap
  zoom_tap_animation: ^1.1.0
  #animation
  animate_do: ^3.3.3
  #shimmer
  shimmer: ^3.0.0
  #toast
  fluttertoast: ^8.2.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf


    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-Black.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-BlackItalic.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-BoldItalic.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-Heavy.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-HeavyItalic.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-Light.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-LightItalic.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-MediumItalic.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-RegularItalic.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-Semibold.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-SemiboldItalic.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-Thin.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-ThinItalic.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-Ultralight.otf
        - asset: assets/fonts/SF_Pro_Display/SF-Pro-Display-UltralightItalic.otf
